# Generated by Django 4.2.4 on 2023-08-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_limited_alter_productimage_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
    ]
