# Generated by Django 4.2.4 on 2023-09-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sort_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.tag'),
        ),
    ]
