# Generated by Django 4.2.4 on 2023-09-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_name_category_title_alter_categoryimage_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='src',
            field=models.ImageField(upload_to=models.ImageField(upload_to='categories/images/'), verbose_name='Ссылка'),
        ),
    ]
