# Generated by Django 4.2.4 on 2023-09-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_categoryimage_src"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryimage",
            name="alt",
            field=models.CharField(default="default", max_length=100),
            preserve_default=False,
        ),
    ]
