# Generated by Django 4.2.4 on 2023-09-05 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_product_sort_index_alter_product_tags'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('deliveryType', models.CharField(max_length=30)),
                ('paymentType', models.CharField(max_length=30)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('products', models.ManyToManyField(related_name='orders', to='products.product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.profile')),
            ],
        ),
    ]
