# Generated by Django 4.2.4 on 2023-09-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderdeliverytype_orderpaymenttype_orderstatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliveryType',
            new_name='deliveryType_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paymentType',
            new_name='paymentType_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='status_id',
        ),
    ]
