# Generated by Django 4.2.4 on 2023-09-07 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_paymenttype_id_alter_order_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentType_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.paymenttype'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.status'),
        ),
    ]
